language: python
python:
 - "3.8"
script:
 - python -m pip install --upgrade pip
 - pip install requests
 - pip install pytest-warnings
 - pip install pytesseract
 - pip install os-win
 - pip install zipfile38
 - pip install googledrivedownloader
 - pip install numpy
 - pip install opencv-python
 - pip install imutils
 - pip install pyTelegramBotAPI
 - pip install tensorflow
 - python Source/build_file.py
