language: python
python:
 - "3.8"
script:
 - pip install pip install opencv-python
 - pip install numpy
 - pip install tensorflow
 - pip install pyTelegramBotAPI
 - pip install imutils
 - pip install pytesseract
 - pip install numpy
 - python -m unittest tests.test_parser
 - python Source/ParseNumplate.py
 - python Source/Tess.py
 - python Source/Prediction.py
 - python Source/Yolo.py
 - python Source/config.py
 - python Source/Bot.py
